#!/usr/bin/env dash

init() {
	apt install -y iptables wireguard qrencode

	echo "net.ipv4.ip_forward = 1" >>/etc/sysctl.conf
	sysctl -p

	SERVER_PRIV_KEY=$(wg genkey)
	SERVER_PUB_KEY=$(echo "$SERVER_PRIV_KEY" | wg pubkey)
	read -rp "Enter VPN name: " SERVER_NAME

	cat <<-EOF >/etc/wireguard/wg0.conf
		[Interface]
		PrivateKey = $SERVER_PRIV_KEY
		Address = 10.0.0.1/24
		ListenPort = 51820
		PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
		PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
	EOF

	cat <<-EOF >/etc/wireguard/params
		SERVER_PUB_KEY=$SERVER_PUB_KEY
		SERVER_IP=$(curl -s ifconfig.co | tr -d '\n')
		SERVER_NAME=$SERVER_NAME
		USED_IPS=1
	EOF

	systemctl enable wg-quick@wg0.service
	systemctl start wg-quick@wg0.service
}

add() {
	CLIENT_NAME=$1
	CLIENT_PRIV_KEY=$(wg genkey)
	CLIENT_PUB_KEY=$(echo "$CLIENT_PRIV_KEY" | wg pubkey)
	USED_IPS=$((USED_IPS + 1))
	CLIENT_IP="10.0.0.$USED_IPS/32"

	mkdir -p "/etc/wireguard/$CLIENT_NAME"

	cat <<-EOF >"/etc/wireguard/$CLIENT_NAME/$SERVER_NAME.conf"
		[Interface]
		PrivateKey = $CLIENT_PRIV_KEY
		Address = $CLIENT_IP

		[Peer]
		PublicKey = $SERVER_PUB_KEY
		Endpoint = $SERVER_IP:51820
		AllowedIPs = 0.0.0.0/0
		PersistentKeepalive = 20
	EOF

	cat <<-EOF >>/etc/wireguard/wg0.conf

		#Client $CLIENT_NAME
		[Peer]
		PublicKey = $CLIENT_PUB_KEY
		AllowedIPs = $CLIENT_IP
	EOF

	sed -i "s/USED_IPS.*/USED_IPS=$USED_IPS/" /etc/wireguard/params

	qrencode -t SVG -o "/etc/wireguard/$CLIENT_NAME/qr.svg" <"/etc/wireguard/$CLIENT_NAME/$SERVER_NAME.conf"

	systemctl restart wg-quick@wg0.service

	echo "Config for $CLIENT_NAME added to /etc/wireguard/$CLIENT_NAME/"

}

remove() {
	CLIENT_NAME=$1
	rm -rf "/etc/wireguard/$CLIENT_NAME"
	sed -i "/#Client $CLIENT_NAME/,/^$/d" /etc/wireguard/wg0.conf
	systemctl restart wg-quick@wg0.service
	echo "Client $CLIENT_NAME removed"
}

list() {
	find /etc/wireguard/ -type d | sed 's/\/etc\/wireguard\///' | sort
}

if [ -r /etc/wireguard/params ]; then
	#shellcheck source=/dev/null
	. /etc/wireguard/params
fi

case $1 in
"-a")
	if [ "$#" -lt 2 ]; then
		echo "Usage: wg-wizard -a <client_name>"
		exit 1
	fi
	add "$2"
	;;
"-r")
	if [ "$#" -lt 2 ]; then
		echo "Usage: wg-wizard -r <client_name>"
		exit 1
	fi
	remove "$2"
	;;
"-l")
	list
	;;
"-i")
	init
	;;
*)
	cat <<EOF
Usage: wg-wizard [options]

Options:
 -a <client_name>  Add new client
 -r <client_name>  Remove client
 -l                List clients
 -i                Setup wireguard
EOF
	exit 1
	;;
esac
